sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t jjacckk/react-docker -f Dockerfile.dev .


script:
  - docker run -e CI=true jjacckk/react-docker npm run test