sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t jjacckk/react-docker -f Dockerfile.dev .


script:
  - docker run -e CI=true jjacckk/react-docker npm run test

deploy:
  provider: elastickbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-886536634566"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY